[build]
  command = "GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES=true gatsby build --log-pages"
  publish = "public"

[dev]
  command = "gatsby develop"

[[plugins]]
  package = "netlify-plugin-gatsby-cache"